#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
#  Syndicate RP — Database Setup Script
#  Creates the MariaDB database, user, and all tables
#
#  Usage: bash scripts/setup-db.sh
#  Requires: MariaDB/MySQL root access
# ─────────────────────────────────────────────────────────

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}[db]${NC} $1"; }
warn() { echo -e "${YELLOW}[warn]${NC} $1"; }
err()  { echo -e "${RED}[error]${NC} $1"; exit 1; }

# ── Prompt for credentials ────────────────────────────────
echo ""
echo "  ╔══════════════════════════════════╗"
echo "  ║  Syndicate RP — Database Setup   ║"
echo "  ╚══════════════════════════════════╝"
echo ""

read -rp "  MariaDB root password: " -s ROOT_PASS
echo ""
read -rp "  New DB password for 'syndicaterp' user: " -s DB_PASS
echo ""
echo ""

# ── Test root connection ──────────────────────────────────
mysql -uroot -p"$ROOT_PASS" -e "SELECT 1;" > /dev/null 2>&1 \
    || err "Cannot connect to MariaDB as root. Is it running?"

log "Connected to MariaDB."

# ── Create DB + user ──────────────────────────────────────
log "Creating database 'syndicaterp'..."
mysql -uroot -p"$ROOT_PASS" <<SQL
CREATE DATABASE IF NOT EXISTS \`syndicaterp\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'syndicaterp'@'localhost'
  IDENTIFIED BY '${DB_PASS}';

GRANT ALL PRIVILEGES ON \`syndicaterp\`.* TO 'syndicaterp'@'localhost';
FLUSH PRIVILEGES;
SQL

log "Database and user created."

# ── Write connection string to server.cfg.local ───────────
CFG_LOCAL="$(dirname "$0")/../server-data/server.cfg.local"

log "Writing connection string to server.cfg.local..."
cat > "$CFG_LOCAL" <<CFG
# ── Secrets — DO NOT COMMIT THIS FILE ────────────────────
# Generated by scripts/setup-db.sh

set mysql_connection_string "mysql://syndicaterp:${DB_PASS}@localhost/syndicaterp?charset=utf8mb4"

# Paste your Cfx.re license key here:
# sv_licenseKey "cfxk_YOUR_KEY_HERE"

# Paste your owner Rockstar license here:
# add_principal identifier.license:YOUR_LICENSE group.superadmin
CFG

log "Written to: $CFG_LOCAL"
warn "server.cfg.local is gitignored — never commit it."

# ── Update server.cfg to exec the local file ─────────────
SERVER_CFG="$(dirname "$0")/../server-data/server.cfg"
if ! grep -q 'exec "server.cfg.local"' "$SERVER_CFG"; then
    # Prepend exec line at top of server.cfg
    sed -i "1s/^/exec \"server.cfg.local\"\n\n/" "$SERVER_CFG"
    log "Added 'exec server.cfg.local' to server.cfg"
fi

echo ""
log "Database setup complete!"
echo ""
echo "  Next:"
echo "  1. Edit server-data/server.cfg.local — add your sv_licenseKey"
echo "  2. Run: bash scripts/install.sh"
echo "  3. Run: bash scripts/start.sh"
echo ""
